CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     owner_id BIGINT REFERENCES users(id) NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description TEXT NOT NULL,
                                     available BOOLEAN,
                                     CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT REFERENCES items(id) NOT NULL,
                                        booker_id BIGINT REFERENCES users(id) NOT NULL,
                                        status VARCHAR(20) NOT NULL,
                                        CONSTRAINT pk_booking PRIMARY KEY (id),
                                        CONSTRAINT chk_booking_status CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        item_id BIGINT REFERENCES items(id) NOT NULL,
                                        author_id BIGINT REFERENCES users(id) NOT NULL,
                                        text TEXT NOT NULL,
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        CONSTRAINT pk_comment PRIMARY KEY (id)
);